# Generated by Django 5.0.4 on 2024-05-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.CharField(default='First_Name', max_length=64),
        ),
    ]
