# Generated by Django 5.0.4 on 2024-05-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_bid_amount_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='amount',
            new_name='listing',
        ),
    ]
