# Generated by Django 5.0.4 on 2024-05-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_amount_bid_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='value',
            new_name='amount',
        ),
    ]
